In [9]:
import pandas as pd
import numpy as np

In [10]:
s1 = pd.Series([1,2,3,4])
s1

0    1
1    2
2    3
3    4
dtype: int64

In [11]:
print(type(s1))

<class 'pandas.core.series.Series'>


In [12]:
s1.values

array([1, 2, 3, 4], dtype=int64)

In [13]:
s1.index.values

array([0, 1, 2, 3], dtype=int64)

In [14]:
s2 = pd.Series([1,2,3,4], ['a', 'b', 'c', 'd'])
s2

a    1
b    2
c    3
d    4
dtype: int64

In [15]:
s3 = pd.Series(np.arange(1, 100, 2), np.arange(1, 51))
s3

1      1
2      3
3      5
4      7
5      9
6     11
7     13
8     15
9     17
10    19
11    21
12    23
13    25
14    27
15    29
16    31
17    33
18    35
19    37
20    39
21    41
22    43
23    45
24    47
25    49
26    51
27    53
28    55
29    57
30    59
31    61
32    63
33    65
34    67
35    69
36    71
37    73
38    75
39    77
40    79
41    81
42    83
43    85
44    87
45    89
46    91
47    93
48    95
49    97
50    99
dtype: int32

In [16]:
# datatype 지정
s4 = pd.Series([1,2,3,4,5], dtype=object)
print(s4)
s5 = pd.Series([1,2,3,4,5], dtype=float)
print(s5)
s6 = pd.Series([1,2,3,4,5], dtype=int)
print(s6)

0    1
1    2
2    3
3    4
4    5
dtype: object
0    1.0
1    2.0
2    3.0
3    4.0
4    5.0
dtype: float64
0    1
1    2
2    3
3    4
4    5
dtype: int32


In [19]:
print(s4.dtype)
s4 = s4.astype('float')
s4

float64


0    1.0
1    2.0
2    3.0
3    4.0
4    5.0
dtype: float64

In [20]:
print(s4.dtype)
s4 = s4.astype('int')
s4

float64


0    1
1    2
2    3
3    4
4    5
dtype: int32

In [21]:
#dictionary
dic_1 = {
    'kor': 90,
    'eng': 95,
    'mat': 87,
    'sci': 88
}
dic_1

{'kor': 90, 'eng': 95, 'mat': 87, 'sci': 88}

In [22]:
s7 = pd.Series(dic_1)
s7

kor    90
eng    95
mat    87
sci    88
dtype: int64

In [23]:
s = pd.Series([1,2,3,4,5], ['a', 'b', 'c', 'd', 'e'])
s

a    1
b    2
c    3
d    4
e    5
dtype: int64

In [24]:
s.index

Index(['a', 'b', 'c', 'd', 'e'], dtype='object')

In [25]:
s.index.values

array(['a', 'b', 'c', 'd', 'e'], dtype=object)

In [26]:
s.values

array([1, 2, 3, 4, 5], dtype=int64)

In [30]:
print(s['b'])
print(s['e'])

2
5


In [34]:
s['b'] = 100
s['e'] = 101
print(s['b'])
print(s['e'])
print(s.values)

100
101
[  1 100   3   4 101]


In [35]:
#index 왕창 변경하기
#변경전 index크기와 변경후의 index크기가 같게 지정해야한다.
s.index = ['가', '나', '다', '라', '마']
s

가      1
나    100
다      3
라      4
마    101
dtype: int64

In [37]:
s['가']

1

In [39]:
#index 재사용
s1 = pd.Series(np.arange(5), s.index)
s1

가    0
나    1
다    2
라    3
마    4
dtype: int32

In [41]:
s1[['나', '라']]

나    1
라    3
dtype: int32

In [42]:
s1['나':'라']

나    1
다    2
라    3
dtype: int32

- 삭제

In [47]:
s1.drop('가')
s1

가    0
다    2
라    3
마    4
dtype: int32

In [45]:
s1.drop('나', inplace=True)
s1

가    0
다    2
라    3
마    4
dtype: int32

In [49]:
s1.drop('다', inplace=True)
s1

가    0
라    3
마    4
dtype: int32

In [50]:
# 바로 삭제
del s1['마']
s1

가    0
라    3
dtype: int32