### Numpy 설치
- pip install numpy

In [3]:
# as np 는 별명(관례적으로 np로 자주 씀)
import numpy as np

In [4]:
# numpy-array(1차원배열)만드는 형태
np.array([1,2,3])
arr # 객체 자체를 출력

array([1, 2, 3])

In [5]:
arr = np.array([1,2,3])
print(arr) # 객체 내부의 값을 출력

[1 2 3]


In [14]:
arr.shape

(3,)

In [6]:
type(arr)

numpy.ndarray

In [11]:
# numpy-array(2차원배열)만드는 형태
arr2 = np.array([[1,2,3],[4,5,6]])

In [12]:
print(arr2)

[[1 2 3]
 [4 5 6]]


In [13]:
arr2.shape #shape는 배열의 행과 열을 나타내 준다

(2, 3)

In [19]:
arr = np.array([[[1,2,3,4],[3,4,5,6],[5,6,7,8]],
          [[7,8,9,10],[9,10,11,12],[11,12,13,14]]])

In [20]:
type(arr)

numpy.ndarray

In [21]:
arr.shape

(2, 3, 4)

arr.shape가 (2,3,3)인 배열 만들기

In [25]:
arr = np.array([[[1,2,3],[2,3,4],[3,4,5]],
               [[5,6,7],[7,8,9],[8,9,10]]])

In [26]:
type(arr)

numpy.ndarray

In [27]:
arr.shape

(2, 3, 3)

In [ ]:
arr3 = np.array([[[1,2,3],[4,5,6],[7,8,9]],
                [[1,2,3],[4,5,6],[7,8,9]],
                [[1,2,3],[4,5,6],[7,8,9]]])

In [ ]:
print(arr3)

#### ndarray 데이터 타입
- https://velog.io/@fiifa92/ndarray%EC%9D%98-%EC%B0%A8%EC%9B%90%EA%B3%BC-%EB%8D%B0%EC%9D%B4%ED%84%B0-%ED%83%80%EC%9E%85
- 숫자, 문자, boolean
- 하나의 데이터 차입만 가짐

In [38]:
arr = np.array([1,2,3])
arr.dtype #dtype은 배열 안의 값의 데이터타입을 출력
# dtype 출력할때 배열의 마지막 값에 대한 데이터타입 출력

dtype('int32')

In [39]:
arr = np.array([1.0,2.0,3.0])
arr.dtype #dtype은 배열 안의 값의 데이터타입을 출력

dtype('float64')

In [40]:
arr = np.array(['1.0','2.0','3.0'])
arr.dtype #dtype은 배열 안의 값의 데이터타입을 출력

dtype('<U3')

In [42]:
arr = np.array([1,2.0,'3'])
arr.dtype #dtype은 배열 안의 값의 데이터타입을 출력
# dtype 출력할때 배열의 마지막 값에 대한 데이터타입 출력

dtype('<U32')

- astype => 데이터 타입 변경

In [43]:
arr = np.array([1,2,3])
print(arr.dtype)

arr2 = arr.astype('float64')
print(arr2)
print(arr2.dtype)

int32
[1. 2. 3.]
float64


In [44]:
arr = np.array(['1','2','3'])
print(arr.dtype)

arr2 = arr.astype('int32')
print(arr2)
print(arr2.dtype)

<U1
[1 2 3]
int32


#### 여러가지 생성 방법

- arange

In [46]:
#range 문
for i in range(1,10):
    print(i)

1
2
3
4
5
6
7
8
9


In [47]:
# arange(n,m) = n부터 (m-1)까지의 배열을 만들어라
np.arange(1,10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [48]:
type(np.arange(1,10))

numpy.ndarray

In [49]:
arr = np.array(np.arange(1,10))
print(arr)

[1 2 3 4 5 6 7 8 9]


- ones

In [50]:
# ones(n,m)은 (n,m)형태의 배열을 만들어라
# 기본형은 float 으로 만들어짐
arr = np.ones((2,3))
print(arr)

[[1. 1. 1.]
 [1. 1. 1.]]


In [51]:
# ones함수에 dtype을 추가해서 데이터 타입 변경가능
arr = np.ones((2,3), dtype=int)
print(arr)

[[1 1 1]
 [1 1 1]]


In [52]:
# ones함수에 dtype을 추가해서 데이터 타입 변경가능
arr = np.ones((6,5), dtype=int)
print(arr)

[[1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]]


- zeros

In [54]:
arr = np.zeros((2,3))
print(arr)

[[0. 0. 0.]
 [0. 0. 0.]]


In [55]:
arr = np.zeros((2,3), dtype=int)
print(arr)

[[0 0 0]
 [0 0 0]]


- empty

In [56]:
# zeros는 0의 값을 만들어서 배열생성하지만
# empty는 메모리 자체의 데이터를 가져와서 배열 생성
arr = np.empty((2,3))
print(arr)

[[0. 0. 0.]
 [0. 0. 0.]]


In [57]:
arr = np.empty((2,3,5))
print(arr)

[[[1.11587377e-311 1.01283457e-321 0.00000000e+000 0.00000000e+000
   8.90105596e-307]
  [5.02034658e+175 2.12815986e+160 1.34994874e+161 1.00465404e-070
   1.57402002e+161]
  [2.59027864e-144 3.80985069e+180 1.14428494e+243 2.59027907e-144
   7.79952704e-143]]

 [[1.02236848e+166 3.21679618e-057 1.39317672e+165 4.08235434e-033
   4.99874559e+217]
  [5.49419094e-143 2.91237123e+257 5.56111702e+180 5.74015544e+180
   1.94919988e-153]
  [2.59027858e-144 2.59903818e-144 4.96803199e-091 1.66050316e-076
   1.45190549e-047]]]


- full

In [58]:
# full((n,m),k) => (2,3)형태의 배열을 k로 채워서 생성
arr = np.full((2,3), 5, dtype=int)
print(arr)

[[5 5 5]
 [5 5 5]]


In [60]:
# full((n,m),k) => (2,3)형태의 배열을 k로 채워서 생성
# k값은 배열로 지정해도 상관없으나 m의 숫자만큼의 배열 생성가능
arr = np.full((2,2), [4,5], dtype=int)
print(arr)

[[4 5]
 [4 5]]
