In [1]:
import numpy as np

In [19]:
#python 자체 내장함수 random패키지 import
import random

# 0과 1 미만 사이의 랜덤값
print(random.random())

#범위(1이상 10미만 중에 2간격으로 random 값 - 정수값 return)
print(random.randrange(1,10,2))

#범위(1이상 10이하 - 정수값 return)
print(random.randint(1,10))

0.30066853980567754
9
2


#### rand : 0과 1사이의 랜덤값(균등분포)

In [26]:
arr = np.random.rand(2,3,4)
print(arr)

[[[0.61811893 0.89650941 0.38917426 0.18641303]
  [0.88052209 0.673536   0.39418722 0.13593431]
  [0.41515931 0.11376239 0.21003293 0.31922056]]

 [[0.97058373 0.18331641 0.81657702 0.33073192]
  [0.10054519 0.73091517 0.7570996  0.18307443]
  [0.49672042 0.37095991 0.21641698 0.37324661]]]


#### randn : 정규분포, 가우시안 분포 난수값

In [32]:
arr = np.random.randn(2,3,4)
print(arr)

[[[ 1.29134689  0.71872367  1.18492304 -0.9281431 ]
  [ 0.0395439  -0.13696967 -0.43912481  0.86008782]
  [ 0.12607289 -1.4299205  -0.01776823 -0.22231777]]

 [[-1.28641965 -0.5999137  -0.59351533 -0.31839544]
  [ 0.41834518 -0.6957467  -0.27768063 -1.45363317]
  [-0.29389454 -1.48377609 -1.36924133 -0.49288208]]]


#### randint : 정수 난수값

- numpy.random.randint(low, high=None, size = None, dtype="I")
- low : 범위의 가장 낮은 값, 파라미터가 1개일 경우 0~low까지
- high : 가장 높은 정수(선택사항)
- size : 반환 개수, array의 shape형태 가능 => size(3,5)
- dtype : int

In [42]:
arr = np.random.randint(3, size=6)
print(arr)

[2 0 2 1 2 1]


In [46]:
arr = np.random.randint(3,10,size=(3,5))
print(arr)

[[6 4 3 8 5]
 [5 9 5 9 3]
 [4 9 7 3 4]]


- seed :  여러번 실행하여도 동일한 난수값

In [54]:
# 처음 출력된 난수값이 코드를 다시 실행시켜도 변하지 않는다
np.random.seed(35)
arr = np.random.randn(2,3)
print(arr)

[[-1.88973671 -0.41359218 -0.76602601]
 [-0.92412667 -1.42159783  0.80525599]]


In [56]:
# 처음 출력된 난수값이 코드를 다시 실행시켜도 변하지 않는다
# 셀이 분리되면 seed가 적용되지않아 다음 셀에서 코드를 실행시킬때 난수값이 변한다.
np.random.seed(35)

In [59]:
arr = np.random.randn(2,3)
print(arr)

[[-0.67615116 -0.16622659  0.46743519]
 [ 0.33371911 -0.84965782  0.06868276]]
