In [13]:
import numpy as np

#### reshape
- 차원과 크기를 변경
- 변경되는 전체의 수가 변경전의 전체수가 동일해야 함
- ndim : 차원수

In [14]:
arr = np.arange(12)
print(arr)
print(arr.shape)
print(arr.ndim)

[ 0  1  2  3  4  5  6  7  8  9 10 11]
(12,)
1


In [15]:
# reshape함수를 사용할때 가장 처음만든 배열의 크기와
#reshape(n,m)에서 n * m 의 크기가 같아야 한다.
arr2 = arr.reshape(3,4)
print(arr2)
print(arr2.shape)
print(arr2.ndim)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
(3, 4)
2


In [16]:
arr3 = arr.reshape(6,2)
print(arr3)
print(arr3.shape)
print(arr3.ndim)

[[ 0  1]
 [ 2  3]
 [ 4  5]
 [ 6  7]
 [ 8  9]
 [10 11]]
(6, 2)
2


In [17]:
arr4 = arr.reshape(2,3,2)
print(arr4)
print(arr4.shape)
print(arr4.ndim)

[[[ 0  1]
  [ 2  3]
  [ 4  5]]

 [[ 6  7]
  [ 8  9]
  [10 11]]]
(2, 3, 2)
3


In [19]:
# 3차원에서 1차원으로도 변경가능하다
arr5 = arr4.reshape(12)
print(arr5)
print(arr5.shape)
print(arr5.ndim)

[ 0  1  2  3  4  5  6  7  8  9 10 11]
(12,)
1


-1을 사용할수 있다.

In [21]:
arr.reshape(-1,3)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [22]:
arr.reshape(-1,6)

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11]])

#### 다차원 배열을 1차원으로
- ravel
- flatten
- reshape
- flatten은 값을 복사해서 새로운 배열을 생성하고 ravel, reshape는 값을 참조하여 생성

In [25]:
arr1 = np.arange(12).reshape(3,4)
print(arr1)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [26]:
arr2 = arr1.ravel()
print(arr2)

[ 0  1  2  3  4  5  6  7  8  9 10 11]


In [27]:
arr3 = arr1.reshape(-1)
print(arr3)

[ 0  1  2  3  4  5  6  7  8  9 10 11]


In [28]:
arr4 = arr1.flatten()
print(arr4)

[ 0  1  2  3  4  5  6  7  8  9 10 11]


- 원본값 변경

In [30]:
arr4[0] = 33

In [31]:
arr4

array([33,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])