In [1]:
import numpy as np

#### 인덱싱
- 단일값 : 인덱스를 이용하여 하나의 데이터에 접근
- 슬라이싱: 연속된 인덱스를 이용하여 여러 데이터에 접근
- 팬시 인덱싱 : 리스트 형태의 인덱스를 이용하여 여러 데이터에 접근
- 불린 인덱싱 : 불린값의 리스트 형태의 인덱스를 이용하여 여러 데이터에 접근
    - 인덱스를 주면 차원이 감소하고 슬라이싱을 하면 차원이 유지됨

#### 단일값
- 1차원

In [2]:
arr = np.arange(1,11)
print(arr)

[ 1  2  3  4  5  6  7  8  9 10]


In [3]:
arr[0]

1

In [4]:
arr.ndim

1

- 2차원

In [21]:
arr = np.arange(1,13).reshape(3,4)
print(arr)
print(arr[1])

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[5 6 7 8]


In [22]:
print(arr[1].shape)
print(arr[1].ndim)

(4,)
1


In [23]:
print(arr[1,2])

7


In [24]:
print(arr[1,-1])

8


In [25]:
arr = np.arange(1,9).reshape(2,2,2)
print(arr)
print(arr.shape)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
(2, 2, 2)


In [27]:
print(arr[1])

[[5 6]
 [7 8]]


In [28]:
print(arr[1,1])

[7 8]


In [29]:
print(arr[1,1,1])

8


#### 슬라이싱
- 1차원

In [30]:
arr = np.arange(1,11)
print(arr)

[ 1  2  3  4  5  6  7  8  9 10]


In [31]:
print(arr[1:5])

[2 3 4 5]


In [32]:
print(arr[2:])

[ 3  4  5  6  7  8  9 10]


In [33]:
print(arr[:8])

[1 2 3 4 5 6 7 8]


In [37]:
print(arr[:-2])

[1 2 3 4 5 6 7 8]


In [38]:
print(arr[1:5].ndim)

1


- 2차원

In [51]:
arr = np.arange(16).reshape(4,-1)
print(arr)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


In [52]:
print(arr[0:2, 1:2])
print(arr[0:2, 1:2].shape)
print(arr[0:2, 1:2].ndim)

[[1]
 [5]]
(2, 1)
2


4,5 / 7,8 가져오기

In [53]:
arr[1:3]

array([[ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [58]:
print(arr[1:3, 1:3])
print(arr[1:3, 1:3].shape)
print(arr[1:3, 1:3].ndim)

[[ 5  6]
 [ 9 10]]
(2, 2)
2


In [59]:
print(arr[2, 1:3])

[ 9 10]


In [61]:
arr[2:4, 2:4]

array([[10, 11],
       [14, 15]])

10, 11, 14, 15 / 9, 10, 11 / 5, 9 / 4, 5, 6, 7

- 3차원

In [63]:
arr = np.arange(27).reshape(3, 3, 3)
print(arr)

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]


In [64]:
print(arr[0:2, 0:2, 0:2])

[[[ 0  1]
  [ 3  4]]

 [[ 9 10]
  [12 13]]]


In [65]:
print(arr[2, 0:2, 0:2])

[[18 19]
 [21 22]]


In [68]:
print(arr[:, :, :])

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]


#### 팬시인덱싱
- 1차원

In [69]:
arr = np.arange(1,11)
print(arr)

[ 1  2  3  4  5  6  7  8  9 10]


In [75]:
arr[8]

9

In [78]:
print(arr[1:5])

[2 3 4 5]


In [79]:
arr = np.arange(1, 10).reshape(3,-1)
print(arr)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [85]:
print(arr[[0,2], 2])

[3 9]


#### 불린인덱싱

In [86]:
arr = np.arange(1,11)
print(arr)

[ 1  2  3  4  5  6  7  8  9 10]


In [88]:
mask = arr > 3
print(mask)

[False False False  True  True  True  True  True  True  True]


In [91]:
arr[mask]

array([ 4,  5,  6,  7,  8,  9, 10])

In [94]:
arr[[False, True, False, False,  True,  True,  True,  True,  True,  True]]

array([ 2,  5,  6,  7,  8,  9, 10])

In [95]:
arr[arr>3]

array([ 4,  5,  6,  7,  8,  9, 10])

#### 여러조건
- and : &
- or : |

In [98]:
mask2 = (arr > 3) & (arr < 7)
print(mask2)

[False False False  True  True  True False False False False]


In [100]:
arr[(arr > 3) & (arr < 7)]

array([4, 5, 6])