In [1]:
import numpy as np

#### 연산
- add
- subtract
- multiply
- divide

- add

In [8]:
arr = np.arange(1, 11).reshape(2,5)
print(arr)
ranarr = np.random.randint(1, 10, size=10).reshape(2, 5)
print(ranarr)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
[[4 6 3 7 6]
 [6 9 6 4 1]]


In [9]:
print(arr + ranarr)

[[ 5  8  6 11 11]
 [12 16 14 13 11]]


In [10]:
print(np.add(arr, ranarr))

[[ 5  8  6 11 11]
 [12 16 14 13 11]]


In [11]:
arr3 = ranarr.reshape(2,5)

In [12]:
print(arr3)

[[4 6 3 7 6]
 [6 9 6 4 1]]


In [13]:
arr-ranarr

array([[-3, -4,  0, -3, -1],
       [ 0, -2,  2,  5,  9]])

In [14]:
np.subtract(arr, ranarr)

array([[-3, -4,  0, -3, -1],
       [ 0, -2,  2,  5,  9]])

In [15]:
arr * ranarr

array([[ 4, 12,  9, 28, 30],
       [36, 63, 48, 36, 10]])

In [16]:
np.multiply(arr, ranarr)

array([[ 4, 12,  9, 28, 30],
       [36, 63, 48, 36, 10]])

In [17]:
arr / ranarr

array([[ 0.25      ,  0.33333333,  1.        ,  0.57142857,  0.83333333],
       [ 1.        ,  0.77777778,  1.33333333,  2.25      , 10.        ]])

In [18]:
np.divide(arr, ranarr)

array([[ 0.25      ,  0.33333333,  1.        ,  0.57142857,  0.83333333],
       [ 1.        ,  0.77777778,  1.33333333,  2.25      , 10.        ]])

sacko.tistory.com/38

In [20]:
arr1 = np.arange(3)
print(arr1)

[0 1 2]


In [21]:
arr1 + 5

array([5, 6, 7])